---
title: "p8105_hw1_ys3765.Rmd"
author: "Yixiao Sun"
date: "2023-09-17"
output: github_document
---

#Problem 1

```{r set up, include= FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r installpackage}
#install.packages("moderndive")
library(tidyverse)
library(moderndive)
```

```{r problem1}
weather_data=get("early_january_weather")
all_variable<-get_all_vars(weather_data)
print(all_variable)
weather_data_row<-nrow(weather_data)
weather_data_col<-ncol(weather_data)
print(weather_data_row)
print(weather_data_col)
timehour_temp_scatterplot<-ggplot(data=weather_data,aes(x=time_hour,y=temp,color=humid))+geom_point()
print(timehour_temp_scatterplot)
ggsave("scatterplot.pdf",plot = timehour_temp_scatterplot)
```

#Problem 2
```{r problem2}
set.seed(123)
df<-data_frame(normal_sample=rnorm(10),logical_vector=normal_sample>0, character_vector = c("1","2","3","4","5","6","7","8","9","10"),factor_vector = factor(sample(1:3,10,replace=TRUE)))

library(tidyverse)

mean_normal_sample <- mean(pull(df, normal_sample))
mean_logical_vector <- mean(pull(df, logical_vector), na.rm = TRUE)
mean_character_vector <- mean(as.numeric(pull(df,character_vector)),na.rm = TRUE)
mean_factor_vector <- mean(as.numeric(pull(df,factor_vector)),na.rm = TRUE)
c(mean_normal_sample, mean_logical_vector, mean_character_vector, mean_factor_vector)

```

